//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRE.SisowV2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="https://www.sisow.nl/Sisow/WebService", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://www.sisow.nl/Sisow/WebService", ConfigurationName="SisowV2.sisowSoap")]
    public interface sisowSoap {
        
        // CODEGEN: Generating message contract since element name issuers from namespace https://www.sisow.nl/Sisow/WebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://www.sisow.nl/Sisow/WebService/GetIssuers", ReplyAction="*")]
        HRE.SisowV2.GetIssuersResponse GetIssuers(HRE.SisowV2.GetIssuersRequest request);
        
        // CODEGEN: Generating message contract since element name transaction from namespace https://www.sisow.nl/Sisow/WebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://www.sisow.nl/Sisow/WebService/GetStatus", ReplyAction="*")]
        HRE.SisowV2.GetStatusResponse GetStatus(HRE.SisowV2.GetStatusRequest request);
        
        // CODEGEN: Generating message contract since element name transaction from namespace https://www.sisow.nl/Sisow/WebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://www.sisow.nl/Sisow/WebService/GetTransaction", ReplyAction="*")]
        HRE.SisowV2.GetTransactionResponse GetTransaction(HRE.SisowV2.GetTransactionRequest request);
        
        // CODEGEN: Generating message contract since element name merchantid from namespace https://www.sisow.nl/Sisow/WebService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://www.sisow.nl/Sisow/WebService/GetURL", ReplyAction="*")]
        HRE.SisowV2.GetURLResponse GetURL(HRE.SisowV2.GetURLRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIssuersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetIssuers", Namespace="https://www.sisow.nl/Sisow/WebService", Order=0)]
        public HRE.SisowV2.GetIssuersRequestBody Body;
        
        public GetIssuersRequest() {
        }
        
        public GetIssuersRequest(HRE.SisowV2.GetIssuersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.sisow.nl/Sisow/WebService")]
    public partial class GetIssuersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool test;
        
        public GetIssuersRequestBody() {
        }
        
        public GetIssuersRequestBody(bool test) {
            this.test = test;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIssuersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetIssuersResponse", Namespace="https://www.sisow.nl/Sisow/WebService", Order=0)]
        public HRE.SisowV2.GetIssuersResponseBody Body;
        
        public GetIssuersResponse() {
        }
        
        public GetIssuersResponse(HRE.SisowV2.GetIssuersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.sisow.nl/Sisow/WebService")]
    public partial class GetIssuersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetIssuersResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public HRE.SisowV2.ArrayOfString issuers;
        
        public GetIssuersResponseBody() {
        }
        
        public GetIssuersResponseBody(int GetIssuersResult, HRE.SisowV2.ArrayOfString issuers) {
            this.GetIssuersResult = GetIssuersResult;
            this.issuers = issuers;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStatus", Namespace="https://www.sisow.nl/Sisow/WebService", Order=0)]
        public HRE.SisowV2.GetStatusRequestBody Body;
        
        public GetStatusRequest() {
        }
        
        public GetStatusRequest(HRE.SisowV2.GetStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.sisow.nl/Sisow/WebService")]
    public partial class GetStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string transaction;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string merchantid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string merchantkey;
        
        public GetStatusRequestBody() {
        }
        
        public GetStatusRequestBody(string transaction, string merchantid, string merchantkey) {
            this.transaction = transaction;
            this.merchantid = merchantid;
            this.merchantkey = merchantkey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStatusResponse", Namespace="https://www.sisow.nl/Sisow/WebService", Order=0)]
        public HRE.SisowV2.GetStatusResponseBody Body;
        
        public GetStatusResponse() {
        }
        
        public GetStatusResponse(HRE.SisowV2.GetStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.sisow.nl/Sisow/WebService")]
    public partial class GetStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetStatusResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string status;
        
        public GetStatusResponseBody() {
        }
        
        public GetStatusResponseBody(int GetStatusResult, string status) {
            this.GetStatusResult = GetStatusResult;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTransactionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTransaction", Namespace="https://www.sisow.nl/Sisow/WebService", Order=0)]
        public HRE.SisowV2.GetTransactionRequestBody Body;
        
        public GetTransactionRequest() {
        }
        
        public GetTransactionRequest(HRE.SisowV2.GetTransactionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.sisow.nl/Sisow/WebService")]
    public partial class GetTransactionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string transaction;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string merchantid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string merchantkey;
        
        public GetTransactionRequestBody() {
        }
        
        public GetTransactionRequestBody(string transaction, string merchantid, string merchantkey) {
            this.transaction = transaction;
            this.merchantid = merchantid;
            this.merchantkey = merchantkey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTransactionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTransactionResponse", Namespace="https://www.sisow.nl/Sisow/WebService", Order=0)]
        public HRE.SisowV2.GetTransactionResponseBody Body;
        
        public GetTransactionResponse() {
        }
        
        public GetTransactionResponse(HRE.SisowV2.GetTransactionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.sisow.nl/Sisow/WebService")]
    public partial class GetTransactionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetTransactionResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string status;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string stamp;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public double amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string account;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string city;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string purchaseid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string description;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string message;
        
        public GetTransactionResponseBody() {
        }
        
        public GetTransactionResponseBody(int GetTransactionResult, string status, string stamp, double amount, string account, string name, string city, string purchaseid, string description, string message) {
            this.GetTransactionResult = GetTransactionResult;
            this.status = status;
            this.stamp = stamp;
            this.amount = amount;
            this.account = account;
            this.name = name;
            this.city = city;
            this.purchaseid = purchaseid;
            this.description = description;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetURLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetURL", Namespace="https://www.sisow.nl/Sisow/WebService", Order=0)]
        public HRE.SisowV2.GetURLRequestBody Body;
        
        public GetURLRequest() {
        }
        
        public GetURLRequest(HRE.SisowV2.GetURLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.sisow.nl/Sisow/WebService")]
    public partial class GetURLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string merchantid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string merchantkey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string payment;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string issuerid;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public long amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string purchaseid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string description;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string entrancecode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string returnurl;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string cancelurl;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string callbackurl;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string notifyurl;
        
        public GetURLRequestBody() {
        }
        
        public GetURLRequestBody(string merchantid, string merchantkey, string payment, string issuerid, long amount, string purchaseid, string description, string entrancecode, string returnurl, string cancelurl, string callbackurl, string notifyurl) {
            this.merchantid = merchantid;
            this.merchantkey = merchantkey;
            this.payment = payment;
            this.issuerid = issuerid;
            this.amount = amount;
            this.purchaseid = purchaseid;
            this.description = description;
            this.entrancecode = entrancecode;
            this.returnurl = returnurl;
            this.cancelurl = cancelurl;
            this.callbackurl = callbackurl;
            this.notifyurl = notifyurl;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetURLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetURLResponse", Namespace="https://www.sisow.nl/Sisow/WebService", Order=0)]
        public HRE.SisowV2.GetURLResponseBody Body;
        
        public GetURLResponse() {
        }
        
        public GetURLResponse(HRE.SisowV2.GetURLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.sisow.nl/Sisow/WebService")]
    public partial class GetURLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetURLResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string trxid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string issuerurl;
        
        public GetURLResponseBody() {
        }
        
        public GetURLResponseBody(int GetURLResult, string trxid, string issuerurl) {
            this.GetURLResult = GetURLResult;
            this.trxid = trxid;
            this.issuerurl = issuerurl;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface sisowSoapChannel : HRE.SisowV2.sisowSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class sisowSoapClient : System.ServiceModel.ClientBase<HRE.SisowV2.sisowSoap>, HRE.SisowV2.sisowSoap {
        
        public sisowSoapClient() {
        }
        
        public sisowSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public sisowSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public sisowSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public sisowSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HRE.SisowV2.GetIssuersResponse HRE.SisowV2.sisowSoap.GetIssuers(HRE.SisowV2.GetIssuersRequest request) {
            return base.Channel.GetIssuers(request);
        }
        
        public int GetIssuers(bool test, out HRE.SisowV2.ArrayOfString issuers) {
            HRE.SisowV2.GetIssuersRequest inValue = new HRE.SisowV2.GetIssuersRequest();
            inValue.Body = new HRE.SisowV2.GetIssuersRequestBody();
            inValue.Body.test = test;
            HRE.SisowV2.GetIssuersResponse retVal = ((HRE.SisowV2.sisowSoap)(this)).GetIssuers(inValue);
            issuers = retVal.Body.issuers;
            return retVal.Body.GetIssuersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HRE.SisowV2.GetStatusResponse HRE.SisowV2.sisowSoap.GetStatus(HRE.SisowV2.GetStatusRequest request) {
            return base.Channel.GetStatus(request);
        }
        
        public int GetStatus(string transaction, string merchantid, string merchantkey, out string status) {
            HRE.SisowV2.GetStatusRequest inValue = new HRE.SisowV2.GetStatusRequest();
            inValue.Body = new HRE.SisowV2.GetStatusRequestBody();
            inValue.Body.transaction = transaction;
            inValue.Body.merchantid = merchantid;
            inValue.Body.merchantkey = merchantkey;
            HRE.SisowV2.GetStatusResponse retVal = ((HRE.SisowV2.sisowSoap)(this)).GetStatus(inValue);
            status = retVal.Body.status;
            return retVal.Body.GetStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HRE.SisowV2.GetTransactionResponse HRE.SisowV2.sisowSoap.GetTransaction(HRE.SisowV2.GetTransactionRequest request) {
            return base.Channel.GetTransaction(request);
        }
        
        public int GetTransaction(string transaction, string merchantid, string merchantkey, out string status, out string stamp, out double amount, out string account, out string name, out string city, out string purchaseid, out string description, out string message) {
            HRE.SisowV2.GetTransactionRequest inValue = new HRE.SisowV2.GetTransactionRequest();
            inValue.Body = new HRE.SisowV2.GetTransactionRequestBody();
            inValue.Body.transaction = transaction;
            inValue.Body.merchantid = merchantid;
            inValue.Body.merchantkey = merchantkey;
            HRE.SisowV2.GetTransactionResponse retVal = ((HRE.SisowV2.sisowSoap)(this)).GetTransaction(inValue);
            status = retVal.Body.status;
            stamp = retVal.Body.stamp;
            amount = retVal.Body.amount;
            account = retVal.Body.account;
            name = retVal.Body.name;
            city = retVal.Body.city;
            purchaseid = retVal.Body.purchaseid;
            description = retVal.Body.description;
            message = retVal.Body.message;
            return retVal.Body.GetTransactionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HRE.SisowV2.GetURLResponse HRE.SisowV2.sisowSoap.GetURL(HRE.SisowV2.GetURLRequest request) {
            return base.Channel.GetURL(request);
        }
        
        public int GetURL(string merchantid, string merchantkey, string payment, string issuerid, long amount, string purchaseid, string description, string entrancecode, string returnurl, string cancelurl, string callbackurl, string notifyurl, out string trxid, out string issuerurl) {
            HRE.SisowV2.GetURLRequest inValue = new HRE.SisowV2.GetURLRequest();
            inValue.Body = new HRE.SisowV2.GetURLRequestBody();
            inValue.Body.merchantid = merchantid;
            inValue.Body.merchantkey = merchantkey;
            inValue.Body.payment = payment;
            inValue.Body.issuerid = issuerid;
            inValue.Body.amount = amount;
            inValue.Body.purchaseid = purchaseid;
            inValue.Body.description = description;
            inValue.Body.entrancecode = entrancecode;
            inValue.Body.returnurl = returnurl;
            inValue.Body.cancelurl = cancelurl;
            inValue.Body.callbackurl = callbackurl;
            inValue.Body.notifyurl = notifyurl;
            HRE.SisowV2.GetURLResponse retVal = ((HRE.SisowV2.sisowSoap)(this)).GetURL(inValue);
            trxid = retVal.Body.trxid;
            issuerurl = retVal.Body.issuerurl;
            return retVal.Body.GetURLResult;
        }
    }
}
